name: Unit Tests - Latest Dependencies
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  unit_tests:
    name: Python ${{ matrix.python_version }} unit tests with Featuretools ${{ matrix.featuretools_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10"]
        featuretools_version: ["main", "release"]
    steps:
      - name: Set up python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build premium primitives package (whl, tar.gz, sdist)
        run: |
          make package
      - name: Install premium primitives via sdist
        run: |
          cd unpacked_sdist
          python -m pip install ".[dev]"
          python -m pip install ".[test]"
      - if: ${{ matrix.featuretools_version == 'main' }}
        name: Install Featuretools from main
        run: |
          python -m pip install -U git+https://github.com/alteryx/featuretools
      - if: ${{ matrix.featuretools_version == 'release' }}
        name: Install latest release of Featuretools
        run: |
          python -m pip install -U featuretools
      - name: Run unit tests
        run: |
          make test
